services:
  mariadb:
    container_name: database
    image: 'mariadb:10.5.9'
    command: '--max_allowed_packet=256M'
    networks:
      - default
    volumes:
      - './data/mariadb:/var/lib/mysql'
    ports:
      - '${MYSQL_PORT_FORWARD}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      TZ: '${TimeZone}'
    restart: always
  litespeed:
    container_name: webserver
    platform: linux/amd64
    image: 'litespeedtech/openlitespeed:1.7.16-lsphp74'
    volumes:
      - './lsws/conf:/usr/local/lsws/conf'
      - './lsws/admin-conf:/usr/local/lsws/admin/conf'
      - './sites:/var/www/vhosts/'
      - './logs:/usr/local/lsws/logs/'
    networks:
      - default
    ports:
      - '80:80'
      - '443:443'
      - '7080:7080'
    environment:
      TZ: '${TimeZone}'
    restart: always
  redis:
    container_name: redis
    image: redis:alpine
    command: redis-server --appendonly yes
    networks:
        - default
    ports:
        - "6379:6379"
    volumes:
        - './data/redis:/data'
    restart: always
    environment:
        - REDIS_REPLICATION_MODE=master
networks:
  default:
    name: server
    driver: bridge
