services:
  database:
    container_name: database
    image: 'mariadb:${MARIADB_VERSION}'
    command: '--max_allowed_packet=1G'
    networks:
      - default
    volumes:
      - './data/mariadb:/var/lib/mysql'
    ports:
      - '${DATABASE_PORT}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      TZ: '${TimeZone}'
    restart: always
  redis:
    container_name: redis
    image: 'redis:${REDIS_VERSION}'
    networks:
      - default
    volumes:
      - './data/redis:/data'
    environment:
      TZ: '${TimeZone}'
    restart: always
  webserver:
    container_name: webserver
    platform: linux/amd64
    image: 'litespeedtech/openlitespeed:${OPENLITESPEED_VERSION}'
    volumes:
      - './lsws/conf:/usr/local/lsws/conf'
      - './lsws/admin-conf:/usr/local/lsws/admin/conf'
      - './sites:/var/www/vhosts/'
      - './logs:/usr/local/lsws/logs/'
    networks:
      - default
    ports:
      - '${WEBSERVER_PORT}:80'
      - '${WEBADMIN_PORT}:7080'
    environment:
      TZ: '${TimeZone}'
    restart: always
  dbms:
    container_name: dbms
    image: phpmyadmin:${PHPMYADMIN_VERSION}
    depends_on:
      - database
    networks:
      - default
    ports:
      - "${DBMS_PORT}:80"
    environment:
      - "PMA_HOST=database"
      - "UPLOAD_LIMIT=1G"
    restart: "always"
networks:
  default:
    name: server
    driver: bridge
